title: Yusuf's CV
profile_img: /assets/img/1Remove background project.png
icon_img: /assets/img/icon.webp

name: "Muhammad Yusuf Kardawi"
job: "AI Research Engineer"

phone_number: +62 822-7777-7807
address: Setiabudi, Jakarta Selatan, Indonesia
email: yusuf.kardawi@jatis.com
linkedin_username: Muhammad Yusuf Kardawi
github_username: yusufkardawi
instagram_username: jusufkardawy
twitter_username: jusufkardawy
facebook_username: Muhammad Yusuf Kardawi
youtube_username: jusufkardawy
blog_url: yusufkardawi.github.io

# If your repo name follows the format "<user-name>.github.io", then leave the below blank.
# Otherwise, set its value as "/<repo-name>". ex) baseurl: /resume
baseurl:

exclude:
  - _posts/
  - resources/
  - vendor/

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
